[build]
  command = "cd HumansVsPokemon && npm install && npm run build"
  publish = "."

[[headers]]
  for = "/*"
  [headers.values]
    Cross-Origin-Opener-Policy = "same-origin"
    Cross-Origin-Embedder-Policy = "require-corp"
